server:
  port: 11001

spring:
  application:
    name: user-services
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DB_PILIPIHU_USER?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimeZone=UTC
    username: root
    password: 113112
    hikari:
      connection-timeout: 3000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis:
  #config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.lyra.app.beans